spotify/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
import notifications.urls

urlpatterns = [
	path('', include('stats.urls')),
    path('admin/', admin.site.urls),
    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

stats/urls.py
# from django.urls import path

from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

app_name = 'stats'
urlpatterns = [

    path('', views.home, name='home'),
    path('auth', views.auth, name='auth'),
    path('refresh', views.refresh_all, name='refresh'),
    path('friends', views.users, name='users'),
    path('add', views.add_friend, name='add_friend'),
    path('add2', views.add2, name='add2'),

    path('new', views.new, name='new'),
    path('graphs', views.graphs, name='graphs'),
    path('search', views.search, name='search'),

    path('media', views.download, name='download'),
    path('logout', views.logout_view, name='logout'),

    path('artist/<str:artist>/', views.artist, name='artist'),
    path('album/<str:album>/', views.album, name='album'),
    path('<str:username>$', views.details, name='details'),
    path('<str:username>/recent/', views.recent, name='recent'),
    path('<str:username>/top/', views.top, name='top'),
    path('<str:username>/saved/', views.saved, name='saved'),
    path('<str:username>/following/', views.following, name='following'),
    path('<str:username>/<str:genre>/', views.genres, name='genres'),
    # url('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_URL}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
# from django.contrib.postgres.fields import ArrayField

# class Question(models.Model):

# 	question_text = models.CharField(max_length=200)
# 	pub_date = models.DateTimeField('date published')

# 	def __str__(self):
# 		return self.question_text

# 	def was_published_recently(self):
# 		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class CustomUserManager(BaseUserManager):

    def _create_user(self, username, password, is_staff, is_superuser, **extra_fields):

        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')

        user = self.model(username=username, is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now, date_joined=now, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        return self._create_user(username, password, False, False, **extra_fields)

    def create_superuser(self, username, password=None, **extra_fields):
        return self._create_user(username, password, True, True, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(max_length=32, blank=True, unique=True)
    email = models.EmailField(max_length=254, blank=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    uri = models.CharField(max_length=48, blank=True)
    # country = models.CharField(max_length=48, blank=True)
    # birthdate = models.CharField(max_length=48, blank=True)
    access_token = models.CharField(max_length=400)
    refresh_token = models.CharField(max_length=400)
    token = models.CharField(max_length=400, blank=True)
    scope = models.CharField(max_length=400, blank=True)

    friends = models.TextField(blank=True, default='')
    
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    # class Meta:
    #     verbose_name = _('user')
    #     verbose_name_plural = _('users')

    def __str__(self):
        return self.username

stats/forms.py
from django import forms
from .models import *

# from django.contrib.auth.forms import

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput())

stats/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render #, get_object_or_404
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
# from django.http import Http404
# from django.urls import reverse
# from django.views import generic
from django.db.models.signals import post_save
from notifications.signals import notify

import io
import os
import time
import json
import spotipy
import requests
from random import random
from collections import Counter

import wikipedia
import networkx as nx
from colorthief import ColorThief
from dateutil.parser import parse
from urllib.request import urlopen
from elasticsearch import Elasticsearch

from .models import CustomUser as User
from .forms import LoginForm

# import plotly.plotly as py
# import plotly.graph_objs as go
# import plotly
# plotly.tools.set_credentials_file(username='armanmann2', api_key='UQYdm8ikKKAL7pLJ7wzp')

# scope = 'user-top-read%20user-follow-read%20user-library-read%20user-read-recently-played%20user-read-email%20streaming'
# url = "https://accounts.spotify.com/authorize/?client_id=" + cid + "&response_type=code&redirect_uri=" + uri + "&scope=" + scope

es = Elasticsearch(['localhost:9200'])

# def my_handler(sender, instance, created, **kwargs):
#     notify.send(instance, verb='was saved')

# post_save.connect(my_handler, sender=User)

def save():
    with open('spotify.txt', 'r') as f:
        data = f.read()

    data = json.loads('[' + data[:-1] + ']')

    for js in data:
        data2 = {
            "grant_type": "refresh_token",
            "refresh_token": js['refresh_token'],
            "client_id": 'e6f5f053a682454ca4eb1781064d3881',
            "client_secret": "e4294f2365ec45c0be87671b0da16596"
        }

        res = requests.post("https://accounts.spotify.com/api/token", data=data2)

        res = requests.get("https://api.spotify.com/v1/me?access_token=" + res.json()['access_token'])
        js1 = res.json()
        print(js1)
        x = User.objects.filter(username=js1['id'])
        if not x:
            print(js1['id'])
            user = User(username=js1['id'], email=js1['email'], uri=js1['uri'], name=js1['display_name'], access_token=js['access_token'], refresh_token=js['refresh_token'], scope=js['scope'])
            user.set_password('password')
            user.save()

def num_format(num):
    return "{:,}".format(num)

def get_time(ms):
    dur = ms/1000
    sec = dur%60
    dur = dur/60
    dur = '%d:%02d'%(dur, sec)
    return dur


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def auth(request):
    code = request.GET['code']
    data = {
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": "http://www.localhost:8000/auth",
        # "redirect_uri": "http://www.soundandcolor.life/auth",
        "client_id": 'e6f5f053a682454ca4eb1781064d3881',
        "client_secret" : "e4294f2365ec45c0be87671b0da16596"
        }

    res = requests.post("https://accounts.spotify.com/api/token", data=data)
    js = res.json()
    res = requests.get("https://api.spotify.com/v1/me?access_token=" + js['access_token'])
    js1 = res.json()
    print("LOGIN:", js1)
    user = User.objects.filter(username=js1['id'])
    if not user:
        user = User(username=js1['id'], email=js1['email'], uri=js1['uri'], name=js1['display_name'], access_token=js['access_token'], refresh_token=js['refresh_token'], scope=js['scope'])
        user.set_password("password")
        user.token = js['access_token']
        #make call to following
        user.save()

        url = "https://api.spotify.com/v1/me/following?type=artist&limit=50&access_token=" + user.token
        res = requests.get(url)
        js = res.json()['artists']
        ids = []
        while True:
            for item in js['items']:
                # if not es.exists('artist', doc_type='_doc', id=item['id']):
                es.index('artist', doc_type='_doc', id=item['id'], body=item)
                ids.append(item['id'])

            if js['next']:
                res = requests.get(js['next']+"&access_token=" + user.token)
                js = res.json()['artists']
            else:
                break
        es.index('following', doc_type='_doc', id=js1['id'], body={'ids':ids})

    else: ######
        user[0].scope = js['scope']
        user[0].save()

    user = authenticate(username=js1['id'], password="password")
    login(request, user)
    refresh(user)
    # return refresh_all()
    return HttpResponseRedirect('/'+user.username+'$')

def refresh(user):
    data = {
        "grant_type": "refresh_token",
        "refresh_token": user.refresh_token,
        "client_id": 'e6f5f053a682454ca4eb1781064d3881',
        "client_secret": "e4294f2365ec45c0be87671b0da16596"
        }

    res = requests.post("https://accounts.spotify.com/api/token", data=data)
    print(res)
    user.token = res.json()['access_token']
    user.save()

def refresh_all(request=None):
    f = User.objects.all()
    users = []
    for user in f:
        refresh(user)
        users.append((user.username, user.email, user.username.split(':')[-1]))
    return HttpResponseRedirect('/friends')

def get_friends(current_user):
    users = []
    if current_user is None:
        fx = User.objects.all()
        for user in fx:
            users.append((user.username, user.email, user.name or user.username))
    else:
        fx = current_user.friends.split(',')[:-1]
        for f in fx:
            user = User.objects.get(username=f)
            users.append((user.username, user.email, user.name or user.username))
    return users

def add2(request):
    current_user = request.user
    btn = request.GET['btn']
    username = request.GET['user']
    print(btn, username)
    notifs = current_user.notifications.unread()
    for n in notifs:
        if str(n).split()[0] == username:
            print('-----', n.actor)
            n.mark_as_read()
    if btn == 'accept':
        current_user.friends += username + ','
        current_user.save()
        user2 = User.objects.get(username=username)
        user2.friends += current_user.username + ','
        user2.save()
    else:
        pass
    return HttpResponseRedirect('/friends')

def add_friend(request):
    current_user = request.user
    username = request.GET['query']
    rec = User.objects.filter(username=username)

    if username and rec and username != current_user.username and username not in current_user.friends.split(',')[:-1]:
        notify.send(current_user, recipient=rec, verb='wants to be friends.')
        message = 'Notification sent.'
    elif not username:
        message = ''
    elif not rec:
        message = "User does not exist. Make sure they've signed up."
    elif username == current_user.username:
        message = 'Lol :)' #####
    else:
        message = 'You are already friends with ' + username + '.'
    return HttpResponseRedirect('/friends?message='+message)

def users(request):
    current_user = request.user
    friends = get_friends(current_user)
    try:
        message = request.GET['message']
    except:
        message = ''

    fids = []
    genres = {}
    for friend in friends:
        try:
            js = get_following(friend[0])
        except:
            continue
        for fid in js:
            fids.append(fid)
            js2 = get_artist(fid)['genres']
            for genre in js2:
                if genre in genres:
                    genres[genre] += 1
                else:
                    genres[genre] = 1
    genres = sorted(genres.items(), key=lambda x: x[1], reverse=True)[:30]
    fids = sorted(Counter(fids).items(), key=lambda x: x[1], reverse=True)[:30]
    fids = [(get_artist(fid[0]), fid[1]) for fid in fids]
    fids = [(a[0]['name'], a[0]['id'], a[1]) for a in fids]

    notifs = []
    for n in current_user.notifications.unread():
        time = str(n).split('. ')
        nn = time[0]
        actor = nn.split()[0]
        time = time[1]
        notifs.append((nn, actor, time))

    return render(request, 'users.html', {'users': friends, 'genres':genres, 'fids':fids, 'notifications':notifs, 'message':message})

def home(request):
    cols = []
    for ch in "Sound & Color":
        cols.append([ch, 20+100*random(), 140+100*random(), 155+100*random()])
    return render(request, 'home.html', {'users': get_friends(None), 'cols':cols})


def get_following(username):
    try:
        return set(es.get('following', doc_type='_doc', id=username)['_source']['ids'])
    except:
        foll, ids = pre_following(username)
        return set(ids)

def get_artist(fid):
    return es.get('artist', doc_type='_doc', id=fid)['_source']

def get_related_artists(artist, token):
    url = "https://api.spotify.com/v1/artists/" + artist + "/related-artists?access_token=" + token
    res = requests.get(url)
    js = res.json()
    es.index('related-artists', doc_type='_doc', id=artist, body=js)
    return js


def details(request, username):
    user = User.objects.get(username=username)
    url = "https://api.spotify.com/v1/me?access_token=" + user.token
    js = requests.get(url).json()
    if 'display_name' not in js:
        refresh(user)
        url = "https://api.spotify.com/v1/me?access_token=" + user.token
        js = requests.get(url).json()

    name = user.name or username
    idd = '' if name == username else username
    email = user.email
    uri = user.uri

    if js['images']:
        img = js['images'][0]['url']
    else:
        img = ''

    genres = {}
    js1 = get_following(username)
    for fid in js1:
        # try:
        js2 = get_artist(fid)['genres']
        # except:
        #     print(fid)
        #     continue
        for genre in js2:
            if genre in genres:
                genres[genre] += 1
            else:
                genres[genre] = 1

stats/templates/stats/album.html
{% extends "base.html" %}
{% load index %}

{%block head %}Album | {{block.super}} {% endblock%}

{% block tron %}
<img src={{ img }}>
<p><font size="+3"><b>{{ name }}</b></font>&emsp;&emsp;&emsp;<font size="+4"><b>{{ pop }}</b></font><br><i>
<!-- {{ type }}<br> -->
{{ date }}</i><br>
{{ genres }}<p>

<p><b>{{ artist }}</b><br>
{{ label }}</p>

<ul>
	{% for key, value in album.items %}
        <li>{{ key }} : {{ value }}</li>
    {% endfor %}
</ul>
<h3>Tracks</h3>
<ol>
	{% for track in tracks %}
        <li><a href={{ track|index:'2' }} target="_blank">{{ track|index:'0' }}</a>&emsp;{{ track|index:'1' }}</li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/artist.html
{% extends "base.html" %}
{% load index %}

{% block tron %}
<table width="100%" cellpadding="10"><tr><td width="55%">
	<img src={{ img }}>

	<p><font size="+3"><b>{{ name }}</b></font>&emsp;&emsp;&emsp;<font size="+5"><b>{{ pop }}</b></font><br>
	<i>{{ foll }}</i></p>

	<p><b><i>{{ genres }}</i></b></p>

	<h3>Top Tracks</h3>
	<ol>
		{% for track in tops %}
	        <li><a href={{ track|index:'2' }} target="_blank">{{ track|index:'0' }}</a>&emsp;{{ track|index:'1' }}</li>
	    {% endfor %}
	</ol>

</td><td valign="top">
	<h3>&emsp;&emsp;Related</h3>
	{% for artist in related %}
    	<img src={{ artist|index:'2' }}></img>&emsp;
		<a href="{% url 'stats:artist' artist|index:'1' %}?token={{ token }}">{{ artist|index:'0' }}</a>
		&emsp;&emsp;&emsp;<font size='+1'>{{ artist|index:'3' }}</font><br>
	{% endfor %}
</td></tr></table>

<h3>Albums</h3>
<ol>
	{% for album in albums %}
        <li><img src={{ album|index:'4' }}>&emsp;<font size="+2"><a href="{% url 'stats:album' album|index:'1' %}?token={{ token }}&play=">{{ album|index:'0' }}</a></font>&emsp;{{ album|index:'2' }}&ensp;-&ensp;{{ album|index:'3' }}</li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/detail.html
{% extends "base.html" %}

{% block tron %}
<h1>{{ question.question_text }}</h1>
<!-- <ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'stats:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

stats/templates/stats/details.html
{% extends "base.html" %}

{% block tron %}

{%if img %}
	<img src={{ img }}>
{% endif %}
<p><font size="+3"><b>{{ name }}</b></font>&emsp;&emsp;&emsp;<i><font size="+1">{{ foll }} Followers</font><br>
{% if id %}
	{{ id }}<br>
{% endif %}
{{ email }}</i></p>

<ul>
	<a href="{% url 'stats:recent' username %}">Recently Played</a><br>
	<a href="{% url 'stats:top' username %}?type=tracks&time=short_term">Top</a><br>
	<a href="{% url 'stats:following' username %}">Following</a><br>
    <a href="{% url 'stats:saved' username %}?type=tracks">Saved Tracks</a><br>
    <a href="{% url 'stats:saved' username %}?type=albums">Saved Albums</a><br><br>
	<br>
    <!-- <a href="{% url 'stats:genres' username %}">Genres</a> -->
</ul>
{% endblock %}

stats/templates/stats/following.html
{% extends "base.html" %}
{% load index %}

{% block tron %}

{% if following %}
    <ol>
    {% for artist in following %}
        <li><img src={{ artist|index:'2' }}></img>&emsp;<font size='+2'><a href="{% url 'stats:artist' artist|index:'1' %}?token={{ token }}">{{ artist|index:'0' }}</a></font>&emsp;&emsp;&emsp;<font size='+3'>{{ artist|index:'3' }}</font></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}

stats/templates/stats/home.html
{% extends "base.html" %}

{% block tron %}
<p><a href = {{ url }}>Log In</a></p>

{% endblock %}

stats/templates/stats/new.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<ol>
	{% for album in new %}
        <li><img src="{{ album|index:'6' }}">&emsp;<font size="+2"><a href="{% url 'stats:album' album|index:'1' %}?token={{ token }}&play=">{{ album|index:'0' }}</a></font>&ensp;-&ensp;{{ album|index:'3' }}&ensp;-&ensp;<a href="{% url 'stats:artist' album|index:'5' %}?token={{ token }}">{{ album|index:'4' }}</a>&ensp;-&ensp;{{ album|index:'2' }}</li><br>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/recent.html
{% extends "base.html" %}
{% load index %}

{% block tron %}

<ol>
	{% for rec in recent %}
        <p><li>{{ rec|index:'7' }}<br><a href="{{ rec|index:'1' }}" target="_blank">{{ rec|index:'0' }}</a>&emsp;//&emsp;<a href="{% url 'stats:artist' rec|index:'3' %}?token={{ token }}">{{ rec|index:'2' }}</a>&emsp;//&emsp;<a href="{% url 'stats:album' rec|index:'5' %}?token={{ token }}">{{ rec|index:'4' }}</a>&emsp;//&emsp;{{ rec|index:'6' }}</li></p>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/saved.html
{% load index %}
<ol>
	{% for track in saved %}
        <li><a href="{{ track|index:'1' }}" target="_blank">{{ track|index:'0' }}</a>&emsp;//&emsp;<a href="{% url 'stats:artist' track|index:'3' %}?token={{ token }}">{{ track|index:'2' }}</a>&emsp;//&emsp;<a href="{% url 'stats:album' track|index:'5' %}?token={{ token }}">{{ track|index:'4' }}</a>&emsp;//&emsp;{{ track|index:'6' }}</li>
    {% endfor %}
</ol>

stats/templates/stats/savedAlbums.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<h3><a href = .?type=tracks>Tracks</a>&emsp;&emsp;Albums</h3>

<ol>
	{% for album in saved %}
        <li><img src="{{ album|index:'5' }}">&emsp;<font size="+2"><a href="{% url 'stats:album' album|index:'1' %}?token={{ token }}&play=">{{ album|index:'0' }}</a></font>&emsp;{{ album|index:'2' }}&ensp;-&ensp;<a href="{% url 'stats:artist' album|index:'4' %}?token={{ token }}">{{ album|index:'3' }}</a></li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/savedTracks.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<h3>Tracks&emsp;&emsp;<a href = .?type=albums>Albums</a></h3>

<ol>
	{% for track in saved %}
        <li><a href="{{ track|index:'1' }}" target="_blank">{{ track|index:'0' }}</a>&emsp;//&emsp;<a href="{% url 'stats:artist' track|index:'3' %}?token={{ token }}">{{ track|index:'2' }}</a>&emsp;//&emsp;<a href="{% url 'stats:album' track|index:'5' %}?token={{ token }}">{{ track|index:'4' }}</a>&emsp;//&emsp;{{ track|index:'6' }}</li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/topArtists.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<h3><a href = ".?type=tracks&time=short_term">Top Tracks</a>&emsp;&emsp;Top Artists</h3>

<p>
	<a href=".?type=artists&time=short_term">Last 4 weeks</a>&emsp;
	<a href=".?type=artists&time=medium_term">Last 6 months</a>&emsp;
	<a href=".?type=artists&time=long_term">All Time</a>
</p>
<br>
<ol>
    {% for artist in tops %}
        <li><img src="{{ artist|index:'2' }}"></img>&emsp;<font size='+2'><a href="{% url 'stats:artist' artist|index:'1' %}?token={{ token }}">{{ artist|index:'0' }}</a></font>&emsp;&emsp;&emsp;<font size='+3'>{{ artist|index:'3' }}</font></li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/topTracks.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<h3>Top Tracks&emsp;&emsp;<a href = ".?type=artists&time=short_term">Top Artists</a></h3>

<p>
	<a href=".?type=tracks&time=short_term">Last 4 weeks</a>&emsp;
	<a href=".?type=tracks&time=medium_term">Last 6 months</a>&emsp;
	<a href=".?type=tracks&time=long_term">All Time</a>
</p>
<br>
<ol>
	{% for top in tops %}
        <li><a href="{{ top|index:'1' }}" target="_blank">{{ top|index:'0' }}</a>&emsp;//&emsp;<a href="{% url 'stats:artist' top|index:'3' %}?token={{ token }}">{{ top|index:'2' }}</a>&emsp;//&emsp;<a href="{% url 'stats:album' top|index:'5' %}?token={{ token }}">{{ top|index:'4' }}</a>&emsp;//&emsp;{{ top|index:'6' }}</li>
    {% endfor %}
</ol>
{% endblock %}

stats/templates/stats/users.html
{% extends "base.html" %}
{% load index %}
{% block tron %}

<!-- <table><tr><td width="50%"> -->

<ol>
	{% for user in users %}
	    <li><a href="{% url 'stats:details' user|index:'2' %}">{{ user|index:'1' }}</a>&emsp;-&emsp;{{ user|index:'2' }}</li>
	{% endfor %}
</ol>

<p>Click <a href ="{% url 'stats:refresh' %}">here</a> to refresh all tokens.</p>

<!-- </td>
<td valign='top' align='center'>
<h3></h3></td></tr>
</table> -->

{% endblock %}